apiVersion: v2
name: opencti
description: A Helm chart to deploy open cyber threat intelligence platform
type: application
maintainers:
  - name: ialejandro
    email: hello@ialejandro.rocks
    url: https://ialejandro.rocks
sources:
  - https://github.com/OpenCTI-Platform/opencti
version: 1.1.2
appVersion: "5.11.13"
home: https://www.filigran.io/en/solutions/products/opencti/
keywords:
  - opencti
dependencies:
  - name: elasticsearch
    version: 19.13.*
    repository: https://charts.bitnami.com/bitnami
    condition: elasticsearch.enabled
  - name: minio
    version: 12.8.*
    repository: https://charts.bitnami.com/bitnami
    condition: minio.enabled
  - name: opensearch
    version: 2.16.*
    repository: https://opensearch-project.github.io/helm-charts/
    condition: opensearch.enabled
  - name: rabbitmq
    version: 12.3.*
    repository: https://charts.bitnami.com/bitnami
    condition: rabbitmq.enabled
  - name: redis
    version: 18.2.*
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled

