apiVersion: v2
description: A Helm chart to deploy Prometheus Prefect Exporter
type: application
maintainers:
  - name: ialejandro
    email: hello@ialejandro.rocks
    url: https://ialejandro.rocks
name: prometheus-prefect-exporter
sources:
  - https://github.com/devops-ia/prometheus-prefect-exporter
version: 1.0.0
appVersion: "1.2.4"
home: https://github.com/devops-ia/helm-charts/tree/main/charts/prometheus-prefect-exporter
keywords:
- prometheus-prefect-exporter
- prometheus
- prefect
