apiVersion: v2
name: cp-schema-registry
description: A Helm chart with cp-schema-registry for Kubernetes
type: application
maintainers:
  - name: ialejandro
    email: hello@ialejandro.rocks
    url: https://ialejandro.rocks
sources:
  - https://github.com/devops-ia/helm-charts/cp-schema-registry
version: 1.0.10
appVersion: 8.1.1-msk-iam-auth2.3.5
home: https://github.com/devops-ia/helm-charts/cp-schema-registry
keywords:
- cp-schema-registry
- confluent
- kafka
- schema-registry
