apiVersion: v2
description: A Helm chart to deploy cronjob to update Amazon ECR token
type: application
maintainers:
  - name: ialejandro
    email: hello@ialejandro.rocks
    url: https://ialejandro.rocks
name: ecr-token
version: 1.0.126
appVersion: awscli2.33.4-kubectl1.35.0
home: https://github.com/devops-ia/helm-charts/tree/main/charts/ecr-token
keywords:
  - aws-ecr
  - ecr
  - token
