{{- if .Values.extraConfig.secrets.enabled }}
{{ range $secrets := .Values.extraConfig.secrets.config }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .name }}
type: {{ .type }}
data:
{{- range $key, $value := $secrets.data }}
  {{ $key }}: |-
{{ tpl $value $ | b64enc | indent 4 }}
{{- end }}

{{- end }}
{{- end }}